id: alien-http-repository-plugin
name: HTTP Artifact Resolver Plugin
version: 1.3.0-RC1-SNAPSHOT
description: >
  Plugin that contains resolver for http artifact
configuration_class: alien4cloud.repository.http.PluginFactoryConfiguration
component_descriptors:
  - bean_name: configurable-http-artifact-resolver-factory
    name: HTTP Configurable Resolver Factory
    description: >
      Factory to create a configurable resolver for HTTP repository
  - bean_name: http-artifact-resolver
    name: HTTP Resolver
    description: >
      Resolver for HTTP repository's artifact